"""init

Revision ID: 3978d85b27ea
Revises: 
Create Date: 2026-02-03 17:28:17.730278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3978d85b27ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspector_fullname', sa.String(), nullable=False),
    sa.Column('standart', sa.String(), nullable=False),
    sa.Column('chemical_composition', sa.String(), nullable=False),
    sa.Column('analysis_result', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alloy_grade', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PASSED', 'FAILED', 'IN_PROGRESS', name='productstatusenum'), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['quality_test.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('quality_test')
    # ### end Alembic commands ###
