"""some fix

Revision ID: 44021ff111d8
Revises: 7ff009e892d6
Create Date: 2026-02-05 21:37:28.891891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44021ff111d8'
down_revision: Union[str, Sequence[str], None] = '7ff009e892d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_test_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'quality_test', ['test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_test_id_fkey'), 'product', 'quality_test', ['test_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
