"""add user

Revision ID: 8117b1d81ff0
Revises: 3978d85b27ea
Create Date: 2026-02-05 16:36:17.277998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8117b1d81ff0'
down_revision: Union[str, Sequence[str], None] = '3978d85b27ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_unique_constraint(None, 'product', ['batch_number'])
    op.drop_constraint(op.f('product_test_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'quality_test', ['test_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_test_id_fkey'), 'product', 'quality_test', ['test_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_table('user')
    # ### end Alembic commands ###
